### ISSUE TITLE
프론트엔드

### ISSUE THREAD

**Issue by Gumball12** [Gumball12/oopsla-static-webpage#1]
### 프론트엔드 해야 할 일 목록

* [ ] 목업 데이터 업데이트

* [ ] 목록 페이지 구현
  * [ ] news
  * [ ] research
  * [ ] people
  * [ ] course

* [ ] 상세 페이지 구현
  * [ ] news
  * [ ] research
  * [ ] people
  * [ ] course

* [ ] 프론트엔드 시연

**Comment by Gumball12** [comment]
## todos
* [ ] 뉴스, 리서치 링크 제대로 (인덱스 사용 말고 제목 이용)
* [ ] 디자인 수정
